# hash:sha256:bb0cb5ad8282a4fe0ba1b016d62b7f25bf2e34e15f3a702fc9d4598afad50af7
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-python3.8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    colorcet==2.0.6 \
    graspologic==0.2.0
