# hash:sha256:00a2355c561d0ffc28a1453ca3ba6bff459b82dd87094be24015a1871bcd3306
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-python3.8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    colorcet \
    graspologic
